#: required

env:
  - DOCKER_COMPOSE_VERSION="1.18.0"

services:
  - docker

before_install:
  -  apt update
  -  rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  -  mv docker-compose /usr/local/bin
  - docker-compose --version

before_script:
  -  make docker-start
  - sleep 2m

script:
  -  make apidoc
  -  make gen-certs
  -  make mysql-dump
  -  make mysql-restore
  -  make phpmd
  -  make test

after_script:
  -  make docker-stop